### ISSUE TITLE
Add environment variables

### ISSUE THREAD

**Issue by patiencedaur** [PiterPy-Meetup/postpost#58]
Add `UPLOADCARE_PUBLIC_KEY` and `UPLOADCARE_SECRET`
(initial install fails without these variables)

**Comment by b0g3r** [comment]
Use https://github.com/henriquebastos/python-decouple with .env files

**Comment by b0g3r** [comment]
reference: https://wemake-django-template.readthedocs.io/en/latest/pages/template/django.html?highlight=python-decouple#secret-settings
